spring:
  application:
    name: Spring-AI-Demo

  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      connect-timeout: 3000
      timeout: 2000
      password: 123456
      username: default

  # 允许Bean定义覆盖
  main:
    allow-bean-definition-overriding: true

  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}
      chat:
        options:
          model: qwen-plus
      embedding:
        options:
          model: text-embedding-v3
      deepSeekModel: deepseek-v3.1

    vectorstore:
      redis:
        initialize-schema: true
        product:
          index-name: product-index
          prefix: product-embedding
          # 自定义索引2：例如用于存储用户相关向量
        user:
          index-name: user-index
          prefix: user-embedding

# RAG检索文档加密密钥
encryption:
  secret-key: my-secret-key

server:
  port: 8081
  servlet:
    context-path: /api
    encoding:
      # 启用字符编码过滤器
      enabled: true
      # 强制使用指定的字符编码
      force: true
      # 设置字符编码为UTF-8
      charset: UTF-8









